[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "--Highlight all the cards used in scoring and play a sound indicating highlight"
position = "before"
match_indent = true
payload = '''
if not SMODS.has_no_rank(scoring_hand[i]) then
  G.GAME.paperback.round.ranks_scored[scoring_hand[i]:get_id()] = (G.GAME.paperback.round.ranks_scored[scoring_hand[i]:get_id()] or 0) + 1
  G.GAME.paperback.ranks_scored_this_ante[scoring_hand[i]:get_id()] = (G.GAME.paperback.ranks_scored_this_ante[scoring_hand[i]:get_id()] or 0) + 1
  G.GAME.paperback.ranks_scored_this_run[scoring_hand[i]:get_id()] = (G.GAME.paperback.ranks_scored_this_run[scoring_hand[i]:get_id()] or 0) + 1
end
if not SMODS.has_no_suit(scoring_hand[i]) then
  if not SMODS.has_any_suit(scoring_hand[i]) then
    for suit, count in pairs(SMODS.Suits) do
      if scoring_hand[i]:is_suit(suit) then
        G.GAME.paperback.round.suits_scored[suit] = (G.GAME.paperback.round.suits_scored[suit] or 0) + 1
        G.GAME.paperback.suits_scored_this_ante[suit] = (G.GAME.paperback.suits_scored_this_ante[suit] or 0) + 1
        G.GAME.paperback.suits_scored_this_run[suit] = (G.GAME.paperback.suits_scored_this_run[suit] or 0) + 1
        break
      end
    end
  end
  if SMODS.has_any_suit(scoring_hand[i]) then
    for suit, count in pairs(SMODS.Suits) do
      G.GAME.paperback.round.suits_scored[suit] = (G.GAME.paperback.round.suits_scored[suit] or 0) + 1
      G.GAME.paperback.suits_scored_this_ante[suit] = (G.GAME.paperback.suits_scored_this_ante[suit] or 0) + 1
      G.GAME.paperback.suits_scored_this_run[suit] = (G.GAME.paperback.suits_scored_this_run[suit] or 0) + 1
    end
  end
end
'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.GAME.round_resets.blind_states.Boss = 'Defeated'"
position = "after"
match_indent = true
payload = '''
G.GAME.paperback.ranks_scored_this_ante = {}
G.GAME.paperback.suits_scored_this_ante = {}
'''
